#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=8g,walltime=2:00:00
#PBS -N app-registration-dwi2anat
#PBS -V


#set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/"
split_b0s=${SCRIPT_DIR}/split_b0s.sh
merge_b0s=${SCRIPT_DIR}/merge_b0s.sh

### === Load parameters from config.json ===
dwi=$(jq -r '.dwi' config.json)
bvals=`jq -r '.bvals' config.json`
bvecs=`jq -r '.bvecs' config.json`
template=`jq -r '.template' config.json`

dwi_b0s=${SCRIPT_DIR}/dwi_b0s.nii.gz
dwi_b0s_bvec=${SCRIPT_DIR}/dwi_b0s.bvecs
dwi_b0s_bval=${SCRIPT_DIR}/dwi_b0s.bvals

singularity exec -e docker://brainlife/mrtrix3:3.0.3 \
  dwiextract -shell 0 -fslgrad $bvecs $bvals $dwi $dwi_b0s -export_grad_fsl $dwi_b0s_bvec $dwi_b0s_bval && mrmath -axis 3  ${dwi_b0s}  mean b0_avg.nii.gz 

mkdir b0

if [ "${template}" == "true" ]; then
  singularity exec -e docker://brainlife/dipy:1.4.1 \
    bash ${split_b0s} $dwi_b0s b0
  singularity exec -e docker://brainlife/ants:2.2.0-1bc \
    bash ${merge_b0s} Template_b  b0_0*.nii.gz
  mv Template_btemplate0.nii.gz b0/dwi.nii.gz
else
  mv b0_avg.nii.gz b0/dwi.nii.gz
fi

mkdir dwi

mv ${dwi_b0s} dwi/dwi.nii.gz
mv ${dwi_b0s_bvec} dwi/dwi.bvals
mv ${dwi_b0s_bval} dwi/dwi.bvals

